config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      post "upvote"
      post "downvote"
    end

    resources :comments, only: [:create, :show] do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
  resources :users, only: [:create, :show]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/users/:id/comments", to: "users#comments", as: "show_comment"
  get "/users/:id/articles", to: "users#articles", as: "show_article"
  get "/users/:id/edit_email", to: "users#edit_email", as: "edit_email_user"
  patch "/users/:id/update_email", to: "users#update_email", as: "update_email_user"
  get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password_user"
  patch "/users/:id/update_password", to: "users#update_password", as: "update_password_user"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # Send email
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
  end

  def edit
    @user = User.find_signed(params[:token], purpose: "password_reset")
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to login_path, notice: "Your password was reset successfully."
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<tr class="header-space"></tr>
<tr>
    <td>
        <h1>Reset your password?</h1>

        <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), method: :patch do |form| %>
            <%= form.label :password %>
            <%= form.password_field :password, placeholder: "Password" %>
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, placeholder: "Confirm Password" %>
            <%= form.submit "Reset Password", class: "btn btn-primary" %>
        <% end %>
    </td>
</tr>

app/views/password_resets/new.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <h1>Forgot your password?</h1>
    <p>Password reset functionality does not work on the deployed version</p>
    <%= form_with url: password_reset_path do |form| %>
      <table class="page-table" width="100%">
        <tbody>
          <tr>
            <td>
              <%= form.label :email %>
            </td>
            <td>
              <%= form.text_field :email, placeholder: "Email" %>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <%= form.submit "Reset Password", class: "btn btn-primary" %>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </td>
</tr>