config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      post "upvote"
      post "downvote"
    end

    resources :comments, only: [:create, :show] do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
  resources :users, only: [:create, :show]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/users/:id/comments", to: "users#comments", as: "show_comment"
  get "/users/:id/articles", to: "users#articles", as: "show_article"
  get "/users/:id/edit_email", to: "users#edit_email", as: "edit_email_user"
  patch "/users/:id/update_email", to: "users#update_email", as: "update_email_user"
  get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password_user"
  patch "/users/:id/update_password", to: "users#update_password", as: "update_password_user"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address"}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:update_email, :update_password]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if user.valid?
      user.save
      redirect_to user
    else
      redirect_to root_path
    end
  end

  def show
  end

  def articles
    @articles = user.articles.order(created_at: :desc).page(params[:page]).per(20)
  end

  def comments
    @comments = user.comments.order(created_at: :desc).page(params[:page]).per(20)
  end

  def edit_email
  end

  def update_email
    if user.update(email_params)
      redirect_to user
    else
      render :edit_email
    end
  end

  def edit_password
  end

  def update_password
    if user.update(password_params)
      redirect_to user
    else
      render :edit_password
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

  def email_params
    params.require(:user).permit(:email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user
    @user ||= User.find(params[:id])
  end
  helper_method :user
end

app/views/users/articles.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <table class="page-table">
      <tbody>
        <% current_page = params[:page].present? ? params[:page].to_i : 1 %>
        <% @articles.each_with_index do |article, index| %>
          <tr>
            <td align="right">
              <span ><%= (current_page-1) * 20 + index + 1 %>.</span>
            </td>
            <td valign="top">
              <center>
                <%= button_to upvote_article_path(article), method: :post, class: "btn btn-sm upvote-button", data: { votable_type: 'Article', votable_id: article.id } do %>
                  <i class="fas fa-arrow-up"></i>
                <% end %>
                <%= button_to downvote_article_path(article), method: :post, class: "btn btn-sm downvote-button", data: { votable_type: 'Article', votable_id: article.id } do %>
                  <i class="fas fa-arrow-down"></i>
                <% end %>
              </center>
            </td>
            <td class="title">
              <%= link_to article.title, article.link, target: "_blank" %>
            </td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td class="subtext">
              <span id="score-Article-<%= article.id %>" class="score"><%= article.score %> points</span>
              by <%= link_to article.user.name, user_path(article.user) %>
              <span class="age"><%= time_ago_in_words(article.created_at) %> ago</span>
              |
              <span class="comments-count"><%= link_to "#{article.comments.count} comments", article %></span>
            </td>
          </tr>
          <tr class="post-subtext"></tr>
        <% end %>
      </tbody>
    </table>
  </td>
</tr>
<tr>
  <td>
    <div class="paginate-spacing">
      <%= paginate @articles %>
    </div>
  </td>
</tr>

app/views/users/comments.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <table class="page-table">
      <tbody>
        <% current_page = params[:page].present? ? params[:page].to_i : 1 %>
        <% @comments.each_with_index do |comment, index| %>
          <tr>  
            <td align="right">
              <span ><%= (current_page-1) * 20 + index + 1 %>.</span>
            </td>  
            <td>
              <center>
                <%= button_to upvote_article_comment_path(comment), method: :post, class: "btn btn-sm upvote-button", data: { votable_type: 'Comment', votable_id: comment.id, article_id: comment.article.id } do %>
                  <i class="fas fa-arrow-up"></i>
                <% end %>
                <%= button_to downvote_article_comment_path(comment), method: :post, class: "btn btn-sm downvote-button", data: { votable_type: 'Comment', votable_id: comment.id, article_id: comment.article.id } do %>
                  <i class="fas fa-arrow-down"></i>
                <% end %>
              </center>
            </td>
            <td>
              <%= comment.text %>
            </td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td class="subtext">
              <span id="score-Comment-<%= comment.id %>"><%= comment.score %> points</span>
              by <%= link_to comment.user.name, user_path(comment.user) %>
              <span class="age"><%= time_ago_in_words(comment.created_at) %> ago</span>
                | 
              <%= link_to(" reply", article_comment_path(comment.article, comment))%>
            </td>
          </tr>
          <tr class="post-subtext"></tr>
        
        <% end %>
      </tbody>
    </table>
  </td>
</tr>
<tr>
  <td>
    <div class="paginate-spacing">
      <%= paginate @comments %>
    </div>
  </td>
</tr>

app/views/users/edit_email.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <h1>Edit Email</h1>

    <%= form_with(model: user, url: update_email_user_path(user), method: :patch) do |form| %>
      <div>
        <%= form.label :email %><br>
        <%= form.email_field :email %>
      </div>

      <div>
        <%= form.submit "Update Email" %>
      </div>
    <% end %>
  </td>
</tr>

app/views/users/edit_password.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <h1>Edit Password</h1>

    <%= form_for user, url: update_password_user_path(user), method: :patch do |f| %>
      <div class="field">
        <div>
            <%= f.label :password %>
        </div>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <%= f.submit "Update Password" %>
      </div>
    <% end %>
  </td>
</tr>

app/views/users/new.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <%= form_for user do |f| %>
      <table class="page-table">
        <tbody>
          <tr>
            <td>
              <%= f.label :name %>
            </td>
            <td>
              <%= f.text_field :name, placeholder: "Username" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :email %>
            </td>
            <td>
              <%= f.text_field :email, placeholder: "Email" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :password %>
            </td>
            <td>
              <%= f.password_field :password, placeholder: "Password" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label :password_confirmation %>
            </td>
            <td>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <%= f.submit "Create Account" %>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </td>
</tr>

app/views/users/show.html.erb
<tr class="header-space"></tr>
<tr>
  <td>
    <table class="page-table">
      <tbody>
        <tr>
          <td>
            <table class="page-table">
              <tbody>
                <tr>
                  <td>
                    <b>User:</b> <%= user.name %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <b>Created:</b> <%= user.created_at.strftime("%B %d, %Y") %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to "Articles", show_article_url %> | 
                    <%= link_to "Comments", show_comment_url %> 
                  </td>
                </tr>
                <% if user == current_user %>
                <tr>
                  <td>
                    <b>Email:</b> <%= user.email %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to "Change Email", edit_email_user_path(user), method: :get %> | 
                    <%= link_to "Change Password", edit_password_user_path(user), method: :get %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </td>
</tr>
<tr class="header-space"></tr>