config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      post "upvote"
      post "downvote"
    end

    resources :comments, only: [:create, :show] do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
  resources :users, only: [:create, :show]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/users/:id/comments", to: "users#comments", as: "show_comment"
  get "/users/:id/articles", to: "users#articles", as: "show_article"
  get "/users/:id/edit_email", to: "users#edit_email", as: "edit_email_user"
  patch "/users/:id/update_email", to: "users#update_email", as: "update_email_user"
  get "/users/:id/edit_password", to: "users#edit_password", as: "edit_password_user"
  patch "/users/:id/update_password", to: "users#update_password", as: "update_password_user"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haxxor News</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <center>
      <table class="page-table" width="85%" style="padding:2px" bgcolor="#f6f6ef">
        <tbody>
          <tr>
            <td bgcolor="#ff6600">
              <table class="page-table" width="100%" style="padding:2px">
                <tbody>
                  <tr>
                    <td style="line-height:12pt; height:10px;">
                      <span class="pagetop">
                        <b class="hnname">
                          <%= link_to 'Haxxor News', root_path %>
                        </b>
                        <%= link_to 'new', new_article_path %>
                      </span>
                    </td>
                    <td style="text-align:right; padding-right:4px;">
                      <div style="display: flex; justify-content: flex-end; gap: 5px;">
                        <span class="pagetop">
                          <% if logged_in? %>
                            <%= link_to current_user.name, user_path(current_user), class: "user-link" %>
                            |
                            <%= link_to "logout", logout_path, method: :delete, class: "logout-link" %>
                          <% else %>
                            <%= link_to "login", login_path, method: :get %>
                            |
                            <%= link_to "signup", signup_path, method: :get %>
                          <% end %>
                        </span>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
          <%= yield %>
        </tbody>
      </table>
    </center>
  </body>
</html>